DROP TABLE IF EXISTS `ref_pays` ;
CREATE TABLE `ref_pays` (
`pays_id` int(11) NOT NULL,
`Libelle` varchar(50) default NULL,
`Libelle_eng` varchar(50) default NULL,
`code` char(3) default NULL,
`code2` char(2) default NULL,
`Capitale` varchar(255) default NULL,
PRIMARY KEY (`pays_id`),
KEY `pays_id` (`pays_id`)
) TYPE=MyISAM;



#
# Dumping data for table 'pays'
#

INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('1', 'Afghanistan', 'Afghanistan', 'AFG', 'AF', 'Kabul');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('2', 'Afrique Du Sud', 'South Africa', 'ZAF', 'ZA', 'Pretoria');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('3', 'Albanie', 'Albania', 'ALB', 'AL', 'Tirane');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('4', 'Algérie', 'Algeria', 'DZA', 'DZ', 'Algers');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('5', 'Allemagne', 'Germany', 'DEU', 'DE', 'Berlin');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('6', 'Andorre', 'Andorra', 'AND', 'AD', 'Andorra la Vella');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('7', 'Angola', 'Angola', 'AGO', 'AO', 'Luanda');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('8', 'Anguilla', 'Anguilla', 'AIA', 'AI', 'The Valley');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('9', 'Antarctique', 'Antarctica', 'ATA', 'AQ', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('10', 'Antigua-et-barbuda', 'Antigua And Barbuda', 'ATG', 'AG', 'St. Johns');



INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('11', 'Antilles Néerlandaises', 'Netherlands Antilles', 'ANT', 'AN', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('12', 'Arabie Saoudite', 'Saudi Arabia', 'SAU', 'SA', 'Riyadh');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('13', 'Argentine', 'Argentina', 'ARG', 'AR', 'Buenos Aires');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('14', 'Arménie', 'Armenia', 'ARM', 'AM', 'Yerevan');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('15', 'Aruba', 'Aruba', 'ABW', 'AW', 'Oranjestad');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('16', 'Australie', 'Australia', 'AUS', 'AU', 'Canberra');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('17', 'Autriche', 'Austria', 'AUT', 'AT', 'Vienna');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('18', 'Azerbaïdjan', 'Azerbaijan', 'AZE', 'AZ', 'Baku');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('19', 'Bahamas', 'Bahamas', 'BHS', 'BS', 'Nassau');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('20', 'Bahreïn', 'Bahrain', 'BHR', 'BH', 'Manama');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('21', 'Bangladesh', 'Bangladesh', 'BGD', 'BD', 'Dhaka');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('22', 'Barbade', 'Barbados', 'BRB', 'BB', 'BrPaysIdgetown');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('23', 'Bélarus', 'Belarus', 'BLR', 'BY', 'Minsk');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('24', 'Belgique', 'Belgium', 'BEL', 'BE', 'Brussels');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('25', 'Belize', 'Belize', 'BLZ', 'BZ', 'Belmopan');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('26', 'Bénin', 'Benin', 'BEN', 'BJ', 'Port-Novo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('27', 'Bermudes', 'Bermuda', 'BMU', 'BM', 'Hamilton');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('28', 'Bhoutan', 'Bhutan', 'BTN', 'BT', 'Thimphu');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('29', 'Bolivie', 'Bolivia', 'BOL', 'BO', 'Sucre');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('30', 'Bosnie-herzégovine', 'Bosnia And Herzegovina', 'BIH', 'BA', 'Sarajevo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('31', 'Botswana', 'Botswana', 'BWA', 'BW', 'Gaborone');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('32', 'Bouvet, Île', 'Bouvet Island', 'BVT', 'BV', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('33', 'Brésil', 'Brazil', 'BRA', 'BR', 'Brasilia');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('34', 'Brunéi Darussalam', 'Brunei Darussalam', 'BRN', 'BN', 'Bander Seri Begawan');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('35', 'Bulgarie', 'Bulgaria', 'BGR', 'BG', 'Sofia');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('36', 'Burkina Faso', 'Burkina Faso', 'BFA', 'BF', 'Ouagadougou');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('37', 'Burundi', 'Burundi', 'BDI', 'BI', 'Bujumbura');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('38', 'Caïmanes, Îles', 'Cayman Islands', 'CYM', 'KY', 'George Town');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('39', 'Cambodge', 'Cambodia', 'KHM', 'KF', 'Phnom Penh');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('40', 'Cameroun', 'Cameroon', 'CMR', 'CM', 'Yaounde');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('41', 'Canada', 'Canada', 'CAN', 'CA', 'Ottawa');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('42', 'Cap-vert', 'Cape Verde', 'CPV', 'CV', 'Praia');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('43', 'Centrafricaine, République', 'Central African Republic', 'CAF', 'CF', 'Bangui');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('44', 'Chili', 'Chile', 'CHL', 'CL', 'Santiago');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('45', 'Chine', 'China', 'CHN', 'CN', 'Beijing');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('46', 'Christmas, Île', 'Christmas Island', 'CXR', 'CX', 'The Settlement');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('47', 'Chypre', 'Cyprus', 'CYP', 'CY', 'Nicosia');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('48', 'Cocos (keeling), Îles', 'Cocos (keeling) Islands', 'CCK', 'CC', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('49', 'Colombie', 'Colombia', 'COL', 'CO', 'Bogota');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('50', 'Comores', 'Comoros', 'COM', 'KM', 'Moroni');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('51', 'Congo', 'Congo', 'COG', 'CG', 'Brazzaville');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('52', 'Congo, La République Démocratique Du', 'Congo, The Democratic Republic Of The', 'COD', 'CD', 'Kinshasa');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('53', 'Cook, Îles', 'Cook Islands', 'COK', 'CK', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('54', 'Corée, République De', 'Korea, Republic Of', 'KOR', 'KR', 'Seoul');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('55', 'Corée, République Populaire Démocratique De', 'Korea, Democratic Peoples Republic Of', 'PRK', 'KP', 'Pyongyang');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('56', 'Costa Rica', 'Costa Rica', 'CRI', 'CR', 'San Jose');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('57', 'Côte Divoire', 'Cote Divoire', 'CIV', 'CI', 'Yamoussoukro');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('58', 'Croatie', 'Croatia', 'HRV', 'HR', 'Zagreb');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('59', 'Cuba', 'Cuba', 'CUB', 'CU', 'Havana');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('60', 'Danemark', 'Denmark', 'DNK', 'DK', 'Copenhagen');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('61', 'Djibouti', 'Djibouti', 'DJI', 'DJ', 'Djibouti');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('62', 'Dominicaine, République', 'Dominican Republic', 'DOM', 'DO', 'Santo Domingo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('63', 'Dominique', 'Dominica', 'DMA', 'DM', 'Roseau');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('64', 'Égypte', 'Egypt', 'EGY', 'EG', 'Cairo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('65', 'El Salvador', 'El Salvador', 'SLV', 'SV', 'San Salvador');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('66', 'Émirats Arabes Unis', 'United Arab Emirates', 'ARE', 'AE', 'Abu Dhabi');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('67', 'Équateur', 'Ecuador', 'ECU', 'EC', 'Quito');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('68', 'Érythrée', 'Eritrea', 'ERI', 'ER', 'Asmara');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('69', 'Espagne', 'Spain', 'ESP', 'ES', 'MadrPaysId');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('70', 'Estonie', 'Estonia', 'EST', 'EE', 'Tallinn');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('71', 'États-unis', 'United States', 'USA', 'US', 'Washington D.C.');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('72', 'Éthiopie', 'Ethiopia', 'ETH', 'ET', 'Addis Ababa');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('73', 'Falkland, Îles (malvinas)', 'Falkland Islands (malvinas)', 'FLK', 'FK', 'Port Stanley');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('74', 'Féroé, Îles', 'Faroe Islands', 'FRO', 'FO', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('75', 'FPaysIdji', 'Fiji', 'FJI', 'FJ', 'Suva');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('76', 'Finlande', 'Finland', 'FIN', 'FI', 'Helsinki');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('77', 'France', 'France', 'FRA', 'FR', 'Paris');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('78', 'Gabon', 'Gabon', 'GAB', 'GA', 'Liberville');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('79', 'Gambie', 'Gambia', 'GMB', 'GM', 'Banjul');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('80', 'Géorgie', 'Georgia', 'GEO', 'GE', 'Tbilisi');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('81', 'Géorgie Du Sud Et Les Îles Sandwich Du Sud', 'South Georgia And The South Sandwich Islands', 'SGS', 'GS', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('82', 'Ghana', 'Ghana', 'GHA', 'GH', 'Accra');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('83', 'Gibraltar', 'Gibraltar', 'GIB', 'GI', 'Gibraltar');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('84', 'Grèce', 'Greece', 'GRC', 'GR', 'Athens');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('85', 'Grenade', 'Grenada', 'GRD', 'GD', 'St. Georges');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('86', 'Groenland', 'Greenland', 'GRL', 'GL', 'Nuuk');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('87', 'Guadeloupe', 'Guadeloupe', 'GLP', 'GP', 'Basse-Terre');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('88', 'Guam', 'Guam', 'GUM', 'GU', 'Agana');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('89', 'Guatemala', 'Guatemala', 'GTM', 'GT', 'Guatemala City');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('90', 'Guinée', 'Guinea', 'GIN', 'GN', 'Conakry');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('91', 'Guinée Équatoriale', 'Equatorial Guinea', 'GNQ', 'GQ', 'Malabo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('92', 'Guinée-bissau', 'Guinea-bissau', 'GNB', 'GW', 'Bissau');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('93', 'Guyana', 'Guyana', 'GUY', 'GY', 'Georgetown');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('94', 'Guyane Française', 'French Guiana', 'GUF', 'GF', 'Conakry');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('95', 'Haïti', 'Haiti', 'HTI', 'HT', 'Port-au-Prince');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('96', 'Heard, Île Et Mcdonald, Îles', 'Heard Island And Mcdonald Islands', 'HMD', 'HM', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('97', 'Honduras', 'Honduras', 'HND', 'HN', 'Tegucigalpa');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('98', 'Hong-kong', 'Hong Kong', 'HKG', 'HK', 'Hong Kong');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('99', 'Hongrie', 'Hungary', 'HUN', 'HU', 'Budapest');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('100', 'Îles Mineures Éloignées Des États-unis', 'United States Minor Outlying Islands', 'UMI', 'UM', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('101', 'Îles Vierges Britanniques', 'Virgin Islands, British', 'VGB', 'VG', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('102', 'Îles Vierges Des États-unis', 'Virgin Islands, U.s.', 'VIR', 'VI', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('103', 'Inde', 'India', 'IND', 'IN', 'New Delhi');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('104', 'Indonésie', 'Indonesia', 'PaysIdN', 'PaysId', 'Jakarta');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('105', 'Iran, République Islamique D', 'Iran, Islamic Republic Of', 'IRN', 'IR', 'Tehran');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('106', 'Iraq', 'Iraq', 'IRQ', 'IQ', 'Baghdad');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('107', 'Irlande', 'Ireland', 'IRL', 'IE', 'Dublin');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('108', 'Islande', 'Iceland', 'ISL', 'IS', 'Reykjavík');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('109', 'Israël', 'Israel', 'ISR', 'IL', 'Jerusalem');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('110', 'Italie', 'Italy', 'ITA', 'IT', 'Rome');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('111', 'Jamaïque', 'Jamaica', 'JAM', 'JM', 'Kingston');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('112', 'Japon', 'Japan', 'JPN', 'JP', 'Tokyo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('113', 'Jordanie', 'Jordan', 'JOR', 'JO', 'Amman');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('114', 'Kazakhstan', 'Kazakhstan', 'KAZ', 'KZ', 'Astana');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('115', 'Kenya', 'Kenya', 'KEN', 'KE', 'Nairobi');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('116', 'Kirghizistan', 'Kyrgyzstan', 'KGZ', 'KG', 'Bishkek');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('117', 'Kiribati', 'Kiribati', 'KIR', 'KI', 'Bairiki');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('118', 'Koweït', 'Kuwait', 'KWT', 'KW', 'Kuwait');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('119', 'Lao, République Démocratique Populaire', 'Lao Peoples Democratic Republic', 'LAO', 'LA', 'Vientiane');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('120', 'Lesotho', 'Lesotho', 'LSO', 'LS', 'Maseru');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('121', 'Lettonie', 'Latvia', 'LVA', 'LV', 'Riga');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('122', 'Liban', 'Lebanon', 'LBN', 'LB', 'Beirut');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('123', 'Libéria', 'Liberia', 'LBR', 'LR', 'Monrovia');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('124', 'Libyenne, Jamahiriya Arabe', 'Libyan Arab Jamahiriya', 'LBY', 'LY', 'Tripoli');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('125', 'Liechtenstein', 'Liechtenstein', 'LIE', 'LI', 'Vaduz');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('126', 'Lituanie', 'Lithuania', 'LTU', 'LT', 'Vilnius');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('127', 'Luxembourg', 'Luxembourg', 'LUX', 'LU', 'Luxembourg');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('128', 'Macao', 'Macao', 'MAC', 'MO', 'Macao');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('129', 'Macédoine, Lex-république Yougoslave De', 'Macedonia, The Former Yugoslav Republic Of', 'MKD', 'MK', 'Skopje');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('130', 'Madagascar', 'Madagascar', 'MDG', 'MG', 'Antananarivo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('131', 'Malaisie', 'Malaysia', 'MYS', 'MY', 'Kuala Lumpur');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('132', 'Malawi', 'Malawi', 'MWI', 'MW', 'Lilongwe');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('133', 'Maldives', 'Maldives', 'MDV', 'MV', 'Malé');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('134', 'Mali', 'Mali', 'MLI', 'ML', 'Bamako');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('135', 'Malte', 'Malta', 'MLT', 'MT', 'Valletta');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('136', 'Mariannes Du Nord, Îles', 'Northern Mariana Islands', 'MNP', 'MP', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('137', 'Maroc', 'Morocco', 'MAR', 'MA', 'Rabat');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('138', 'Marshall, Îles', 'Marshall Islands', 'MHL', 'MH', 'Majuro');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('139', 'Martinique', 'Martinique', 'MTQ', 'MQ', 'Fort-de-France');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('140', 'Maurice', 'Mauritius', 'MUS', 'MU', 'Port Louis');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('141', 'Mauritanie', 'Mauritania', 'MRT', 'MR', 'Nouakchott');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('142', 'Mayotte', 'Mayotte', 'MYT', 'YT', 'Mamoudzou');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('143', 'Mexique', 'Mexico', 'MEX', 'MX', 'Mexico City');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('144', 'Micronésie, États Fédérés De', 'Micronesia, Federated States Of', 'FSM', 'FM', 'Palikir');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('145', 'Moldova, République De', 'Moldova, Republic Of', 'MDA', 'MD', 'Chisinau');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('146', 'Monaco', 'Monaco', 'MCO', 'MC', 'Monaco');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('147', 'Mongolie', 'Mongolia', 'MNG', 'MN', 'Ulaanbaatar');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('148', 'Montserrat', 'Montserrat', 'MSR', 'MS', 'Plymouth');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('149', 'Mozambique', 'Mozambique', 'MOZ', 'MZ', 'Maputo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('150', 'Myanmar', 'Myanmar', 'MMR', 'MM', 'Yangôn');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('151', 'Namibie', 'Namibia', 'NAM', 'NA', 'Windhoek');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('152', 'Nauru', 'Nauru', 'NRU', 'NR', 'Yaren');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('153', 'Népal', 'Nepal', 'NPL', 'NP', 'Kathmandu');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('154', 'Nicaragua', 'Nicaragua', 'NIC', 'NI', 'Managua');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('155', 'Niger', 'Niger', 'NER', 'NE', 'Niamey');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('156', 'Nigéria', 'Nigeria', 'NGA', 'NG', 'Abuja');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('157', 'Niué', 'Niue', 'NIU', 'NU', 'Alofi');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('158', 'Norfolk, Île', 'Norfolk Island', 'NFK', 'NF', 'Kingston');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('159', 'Norvège', 'Norway', 'NOR', 'NO', 'Oslo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('160', 'Nouvelle-calédonie', 'New Caledonia', 'NCL', 'NC', 'Noumea');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('161', 'Nouvelle-zélande', 'New Zealand', 'NZL', 'NZ', 'Wellington');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('162', 'Océan Indien, Territoire Britannique De L', 'British Indian Ocean Territory', 'IOT', 'IO', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('163', 'Oman', 'Oman', 'OMN', 'OM', 'Muscat');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('164', 'Ouganda', 'Uganda', 'UGA', 'UG', 'Kampala');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('165', 'Ouzbékistan', 'Uzbekistan', 'UZB', 'UZ', 'Tashkent');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('166', 'Pakistan', 'Pakistan', 'PAK', 'PK', 'Islamabad');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('167', 'Palaos', 'Palau', 'PLW', 'PW', 'Koror');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('168', 'Palestinien Occupé, Territoire', 'Palestinian Territory, Occupied', 'PSE', 'PS', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('169', 'Panama', 'Panama', 'PAN', 'PA', 'Panama City');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('170', 'Papouasie-nouvelle-guinée', 'Papua New Guinea', 'PNG', 'PG', 'Port Moresby');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('171', 'Paraguay', 'Paraguay', 'PRY', 'PY', 'Asunción');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('172', 'Pays-bas', 'Netherlands', 'NLD', 'NL', 'Amsterdam');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('173', 'Pérou', 'Peru', 'PER', 'PE', 'Lima');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('174', 'Philippines', 'Philippines', 'PHL', 'PH', 'Manila');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('175', 'Pitcairn', 'Pitcairn', 'PCN', 'PN', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('176', 'Pologne', 'Poland', 'POL', 'PL', 'Warsaw');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('177', 'Polynésie Française', 'French Polynesia', 'PYF', 'PF', 'Papeete');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('178', 'Porto Rico', 'Puerto Rico', 'PRI', 'PR', 'San Juan');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('179', 'Portugal', 'Portugal', 'PRT', 'PT', 'Lisbon');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('180', 'Qatar', 'Qatar', 'QAT', 'QA', 'Doha');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('181', 'Réunion', 'Reunion', 'REU', 'RE', 'Saint-Deni');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('182', 'Roumanie', 'Romania', 'ROM', 'RO', 'Bucharest');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('183', 'Royaume-uni', 'United Kingdom', 'GBR', 'GB', 'London');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('184', 'Russie, Fédération De', 'Russian Federation', 'RUS', 'RU', 'Moscow');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('185', 'Rwanda', 'Rwanda', 'RWA', 'RW', 'Kigali');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('186', 'Sahara OccPaysIdental', 'Western Sahara', 'ESH', 'EH', 'Laayoune');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('187', 'Saint-kitts-et-nevis', 'Saint Kitts And Nevis', 'KNA', 'KN', 'Basseterre');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('188', 'Saint-marin', 'San Marino', 'SMR', 'SM', 'San Marino');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('189', 'Saint-pierre-et-miquelon', 'Saint Pierre And Miquelon', 'SPM', 'PM', 'Saint Pierre');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('190', 'Saint-siège (état De La Cité Du Vatican)', 'Holy See (vatican City State)', 'VAT', 'VA', 'Vatican');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('191', 'Saint-vincent-et-les Grenadines', 'Saint Vincent And The Grenadines', 'VCT', 'VC', 'Kingstown');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('192', 'Sainte-hélène', 'Saint Helena', 'SHN', 'SH', 'Jamestown');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('193', 'Sainte-lucie', 'Saint Lucia', 'LCA', 'LC', 'Castries');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('194', 'Salomon, Îles', 'Solomon Islands', 'SLB', 'SB', 'Honiara');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('195', 'Samoa', 'Samoa', 'WSM', 'WS', 'Apia');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('196', 'Samoa Américaines', 'American Samoa', 'ASM', 'AS', 'Pago Pago');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('197', 'Sao Tomé-et-principe', 'Sao Tome And Principe', 'STP', 'ST', 'São Tomé');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('198', 'Sénégal', 'Senegal', 'SEN', 'SN', 'Dakar');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('199', 'Seychelles', 'Seychelles', 'SYC', 'CS', 'Victoria');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('200', 'Sierra Leone', 'Sierra Leone', 'SLE', 'SC', 'Freetown');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('201', 'Singapour', 'Singapore', 'SGP', 'SG', 'Singapore');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('202', 'Slovaquie', 'Slovakia', 'SVK', 'SK', 'Bratislava');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('203', 'Slovénie', 'Slovenia', 'SVN', 'SI', 'Ljubljana');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('204', 'Somalie', 'Somalia', 'SOM', 'SO', 'Mogadishu');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('205', 'Soudan', 'Sudan', 'SDN', 'SD', 'Khartoum');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('206', 'Sri Lanka', 'Sri Lanka', 'LKA', 'LK', 'Colombo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('207', 'Suède', 'Sweden', 'SWE', 'SE', 'Stockholm');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('208', 'Suisse', 'Switzerland', 'CHE', 'CH', 'Bern');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('209', 'Suriname', 'Suriname', 'SUR', 'SR', 'Paramaribo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('210', 'Svalbard Et Île Jan Mayen', 'Svalbard And Jan Mayen', 'SJM', 'SJ', 'Longyearbyen');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('211', 'Swaziland', 'Swaziland', 'SWZ', 'SZ', 'Mbabane');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('212', 'Syrienne, République Arabe', 'Syrian Arab Republic', 'SYR', 'SY', 'Damascus');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('213', 'Tadjikistan', 'Tajikistan', 'TJK', 'TJ', 'Dushanbe');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('214', 'Taïwan, Province De Chine', 'Taiwan, Province Of China', 'TWN', 'TW', 'Taipei');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('215', 'Tanzanie, République-unie De', 'Tanzania, United Republic Of', 'TZA', 'TZ', 'Dodoma');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('216', 'Tchad', 'Chad', 'TCD', 'TD', 'NDjamena');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('217', 'Tchèque, République', 'Czech Republic', 'CZE', 'CZ', 'Prague');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('218', 'Terres Australes Françaises', 'French Southern Territories', 'ATF', 'TF', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('219', 'Thaïlande', 'Thailand', 'THA', 'TH', 'Bangkok');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('220', 'Timor-leste', 'Timor-leste', 'TMP', 'TL', 'Dili');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('221', 'Togo', 'Togo', 'TGO', 'TG', 'Lome');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('222', 'Tokelau', 'Tokelau', 'TKL', 'TK', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('223', 'Tonga', 'Tonga', 'TON', 'TO', 'Nukualofa');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('224', 'Trinité-et-tobago', 'TrinPaysIdad And Tobago', 'TTO', 'TT', 'Port of Spain');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('225', 'Tunisie', 'Tunisia', 'TUN', 'TN', 'Tunis');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('226', 'Turkménistan', 'Turkmenistan', 'TKM', 'TM', 'Ashgabat');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('227', 'Turks Et Caïques, Îles', 'Turks And Caicos Islands', 'TCA', 'TC', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('228', 'Turquie', 'Turkey', 'TUR', 'TR', 'Ankara');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('229', 'Tuvalu', 'Tuvalu', 'TUV', 'TV', 'Funafuti');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('230', 'Ukraine', 'Ukraine', 'UKR', 'UA', 'Kiev');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('231', 'Uruguay', 'Uruguay', 'URY', 'UY', 'MontevPaysIdeo');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('232', 'Vanuatu', 'Vanuatu', 'VUT', 'VU', 'Port Vila');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('233', 'Venezuela', 'Venezuela', 'VEN', 'VE', 'Caracas');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('234', 'Viet Nam', 'Viet Nam', 'VNM', 'VN', 'Hanoi');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('235', 'Wallis Et Futuna', 'Wallis And Futuna', 'WLF', 'WF', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('236', 'Yémen', 'Yemen', 'YEM', 'YE', 'Sana');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('237', 'Yougoslavie', 'Yugoslavia', 'YUG', 'YU', NULL);
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('238', 'Zambie', 'Zambia', 'ZMB', 'ZM', 'Lusaka');
INSERT INTO ref_pays  (PaysId, Libelle, LibelleEng, code, code2, Capitale) VALUES('239', 'Zimbabwe', 'Zimbabwe', 'ZWE', 'ZW', 'Harare');